config/routes.rb
Rails.application.routes.draw do
  
#   constraints(host: /^(?!www\.)/i) do
#     get '(*any)' => redirect { |params, request|
#       URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
#     }
#   end
  
#   constraints subdomain: "" do   
#     get "/" => redirect { |params, request|
#       URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
#     }
#   end

  # TODO /admin/comments-management
  get '/comments' => 'visitors#comments'

  resources :categories
  resources :episodes
  resources :series

  get '/series/genre/:search' => 'series#genre', :as => :genre

  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  get '/load_tile/:id', to: 'series#load_tile', as: 'load_tile'
  get '/load_tile_cover/:id', to: 'series#load_tile_cover', as: 'load_tile_cover'
end

app/controllers/visitors_controller.rb
require 'will_paginate/array'

class VisitorsController < ApplicationController

  def index
    @series = Series.all_ordered_by_child.to_a.paginate(page: params[:page], per_page: 12)
    @series_presenter = SeriesPresenter.instantiate(@series.reverse)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def comments
    page_error_or_missing unless admin?
  end

  private

  def page_error_or_missing
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end

end

app/views/visitors/_slider.html.haml
.container
  .row
    #posts
      - @series_presenter.each do |series|
        = render 'visitors/tile', series: series

app/views/visitors/_tile.html.haml
.col-sm-6.col-md-4.col-mlg-4.col-lg-3
  .panel.panel-default.tile-block.border-radius-5
    .panel-body.hover-tile
      = link_to series_path(series.native) do
        .cover-image{class: "series_#{series.native.id}"}
          :javascript
              addPostponedFunc(['allScriptsReady'],function(){
                if (window.series_#{series.native.id} != undefined) {
                  $(".series_#{series.native.id}")
                    .empty()
                    .append(window.series_#{series.native.id})
                    .find('.inside-image')
                    .fadeIn( 1000 );
                } else {
                  $.getScript('#{ load_tile_path(series.native) }');
                }
              })
          .corner{class: "corner-category_#{series.native.category_id}"}
      .padding-div
        %h4.tall
          %span.big
            = link_to series.name, series_path(series.native)
        %div
          %i.mdi-av-movie.mdi-material-grey-700.vertical-middle
          %span
            %b= series.tile_episode_counter
        %div.last-ep-name
          %span= "#{series.tile_last_ep_name}"
        %div.views-section
          %span.pull-left.views-span
            %i.mdi-action-visibility.vertical-middle
            = series.views
          %span.pull-right.days-span= "#{series.amount_of_days} тому"

app/views/visitors/comments.html.haml
.well.bs-component
  #vk_all_comments

app/views/visitors/index.html.haml
.row
  .col-sm-12
    %ul.breadcrumb
      %li
        = link_to 'Головна', root_path
      %li.active Останні надходження
.row
  .col-lg-9
    = render 'visitors/slider'
    .center-block{style: 'width:143px; height: 78px'}
      #infinite-scrolling
        = will_paginate @series, class: 'hidden-element paginate'
      .btn-group.pull-left
        %a#load_more_titles.btn.btn-default{onclick: 'Paginate.loadMore()'}
          %i.mdi-notification-sync{style: 'vertical-align: middle'}
          %span Більше
  .col-lg-3
    .panel.panel-info
      .panel-body
        .col-12
          %a.twitter-timeline{"data-dnt" => "true", "data-lang" => "uk", "data-link-color" => "#03a9f4", "data-chrome"=>"nofooter noborders transparent", "data-tweet-limit"=>"3", :href => "https://twitter.com/UkrDub?ref_src=twsrc%5Etfw"} Tweets by UkrDub

app/views/visitors/index.js.erb
$('.hidden-element.paginate').replaceWith('<%= j will_paginate @series, class: 'hidden-element paginate' %>');
$('#posts').append('<%= j render partial: 'visitors/slider' %>');