config/routes.rb
Rails.application.routes.draw do
  
#   constraints(host: /^(?!www\.)/i) do
#     get '(*any)' => redirect { |params, request|
#       URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
#     }
#   end
  
#   constraints subdomain: "" do   
#     get "/" => redirect { |params, request|
#       URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
#     }
#   end

  # TODO /admin/comments-management
  get '/comments' => 'visitors#comments'

  resources :categories
  resources :episodes
  resources :series

  get '/series/genre/:search' => 'series#genre', :as => :genre

  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  get '/load_tile/:id', to: 'series#load_tile', as: 'load_tile'
  get '/load_tile_cover/:id', to: 'series#load_tile_cover', as: 'load_tile_cover'
end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_nested_set
  has_many :series
end

app/controllers/categories_controller.rb
require 'will_paginate/array' 
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    with_children_ids = children.map(&:id).push(@category.id).sort
    if params[:search]
      @series = Series.all_ordered_by_child.where(category_id: with_children_ids).search(params[:search]).to_a.paginate(page: params[:page], per_page: 9)
    else
      @series = Series.all_ordered_by_child.where(category_id: with_children_ids).to_a.paginate(page: params[:page], per_page: 9)
    end
    @series_presenter = SeriesPresenter.instantiate(@series.reverse)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def children
      @category.children
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :desc)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def grouped_options(id)
    puts id
    html = ''
    Category.where(depth: 0).sort.each{|cat| html += yyy(cat, id) }
    html.html_safe
  end

  private

  # def childrens c
  #   if c.children.present?
  #     c.children.map{|child| [child.name, "#{child.id}"]}
  #   else
  #     "#{c.id}"
  #   end
  # end

  def yyy(c, id)
    if c.children.present?
      cc = ''
      c.children.each {|child| cc += "<option value='#{child.id}' #{ child.id.to_i == id.to_i ? 'selected=selected' : '' }>#{child.name}</option>" }
      "<optgroup label='#{c.name}'>#{cc}</optgroup>"

    else
      "<option value='#{c.id}' #{c.id.to_i == id.to_i ? 'selected=selected' : ''}>#{c.name}</option>"
    end

  end

end

app/views/categories/_form.html.haml
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :desc

  .form-actions
    = f.button :submit

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
.row
  .col-sm-12
    %ul.breadcrumb
      %li
        = link_to 'Головна', root_path
      %li.active Аніме
.row
  .col-lg-8
    - @series_presenter.each do |series_presenter|
      = render 'series/single_post', series_presenter: series_presenter
    %br
    = link_to 'New Series', new_series_path



  .col-lg-4
    = render 'layouts/last_comments'

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
- content_for :title do
  = @category.name
- content_for :description do
  = "#{@category.name} - UkrDub - це вітчизняний фандаб проект, що займається перекладом і озвученням аніме та серіалів українською мовою." 
- content_for :url do
  = request.original_url  
  
.row
  .col-sm-12
    %ul.breadcrumb
      %li
        = link_to 'Головна', root_path
      - if @category.parent
        %li
          = link_to @category.parent.try(:name), category_path(@category.parent)
      %li.active= @category.name
.row
  .col-lg-8
    - @series_presenter.each do |series_presenter|
      = render 'series/single_post', series_presenter: series_presenter
    %br
    .center-block{style: 'height: 78px'}
      = will_paginate @series, renderer: BootstrapPagination::Rails

  .col-lg-4
    = render 'layouts/last_comments'

:css
  .corner {
    display: none;
  }