config/routes.rb
Rails.application.routes.draw do
  
#   constraints(host: /^(?!www\.)/i) do
#     get '(*any)' => redirect { |params, request|
#       URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
#     }
#   end
  
#   constraints subdomain: "" do   
#     get "/" => redirect { |params, request|
#       URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
#     }
#   end

  # TODO /admin/comments-management
  get '/comments' => 'visitors#comments'

  resources :categories
  resources :episodes
  resources :series

  get '/series/genre/:search' => 'series#genre', :as => :genre

  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  get '/load_tile/:id', to: 'series#load_tile', as: 'load_tile'
  get '/load_tile_cover/:id', to: 'series#load_tile_cover', as: 'load_tile_cover'
end

app/controllers/series_controller.rb
require 'will_paginate/array'

class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy, :load_tile, :load_tile_cover]
  before_filter :authenticate_user!, except: [:show, :index, :load_tile, :load_tile_cover, :genre]
  before_filter :check_permissions, except: [:show, :index, :load_tile, :load_tile_cover, :genre]

  # GET /series
  # GET /series.json

  def index
    if params[:search]
      @series = Series.all_ordered_by_child.search(params[:search]).to_a.paginate(page: params[:page], per_page: 9)
    else
      @series = Series.all_ordered_by_child.to_a.paginate(page: params[:page], per_page: 9)
    end
    @series_presenter = SeriesPresenter.instantiate(@series)
  end

  def load_tile
    @series_presenter = SeriesPresenter.new(@series)
  end

  def load_tile_cover
    @series_presenter = SeriesPresenter.new(@series)
  end

  # GET /series/1
  # GET /series/1.json
  def show
    @episodes = @series.episodes
    @series_presenter = SeriesPresenter.new(@series)
    @episodes_presenter = EpisodePresenter.instantiate(@series.episodes)
    @series.increment
  end

  def genre
    if params[:search]
      @series = Series.all_ordered_by_child.genre(params[:search]).to_a.paginate(page: params[:page], per_page: 9)
    else
      @series = Series.all_ordered_by_child.to_a.paginate(page: params[:page], per_page: 9)
    end
    @series_presenter = SeriesPresenter.instantiate(@series)
    render :index
  end

  # GET /series/new
  def new
    @series = Series.new
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # GET /series/1/edit
  def edit
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # POST /series
  # POST /series.json
  def create
    @categories = Category.all.map{|c| [ c.name, c.id ] }
    @series = Series.new(series_params)
    @series.category_id = params[:series][:category_id]
    respond_to do |format|
      if @series.valid? && @series.save
        format.html { redirect_to @series, notice: 'Series was successfully created.' }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      @categories = Category.all.map{|c| [ c.name, c.id ] }
      @series.category_id = params[:category_id]
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_index_url, notice: 'Series was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(
          :name, :description, :cover,
          :episodes_amount,
          :torrent, :episode_time, :year,
          :studio_name, :video_info,
          :audio_info, :translator, :actors,
          :sound_maker, :source_mirror,
          :source_mirror_additional,
          :tag_list, :executer,
          :original_name,
          :category_id,
          episodes_attributes: episode_params
      )
    end

    def episode_params
      [:id, :episode_number, :name, :video_link, :_destroy]
    end
end

app/helpers/series_helper.rb
module SeriesHelper

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to(name, 'javascript: void(0)', onclick: 'removeFields(this)')
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to('javascript:void(0)', onclick: "addFields(this, '#{association}', '#{escape_javascript(fields)}')", class: 'adder btn btn-info') do
      '<i class="mdi-content-add"></i>'.html_safe + name
    end
  end

end

app/views/series/_cover_ajax.html.haml
.inside-image{style: "background-image: url('#{cover.url(secure: true).sub('/upload/', '/upload/')}');background-size:cover;background-position: 100% 5%"}
.corner{class: "corner-category_#{category_id}"}

app/views/series/_cover_url_ajax.html.haml
'#{cover.url(secure: true)}'

app/views/series/_downloads_panel.html.haml
.download-panel
  .panel.panel-info
    .panel-body
      %h4 Інші джерела
      .list-group
        - if @series_presenter.torrent
          = link_to @series_presenter.torrent, class: 'btn special-button', target: '_blank' do
            .list-group-item
              .row-action-primary
                %i.mdi-file-cloud-circle.torrent
              .row-content
                .action-secondary
                  %i.mdi-file-file-download
                %h4.list-group-item-heading
                  \посилання на .torrent
                %p.list-group-item-text Торрент трекер
          .list-group-separator
        - if @series_presenter.source_mirror
          = link_to @series_presenter.source_mirror, target: '_blank', class: 'btn special-button' do
            .list-group-item
              .row-action-primary
                %i.mdi-notification-folder-special.ex-ua
              .row-content
                .action-secondary
                  %i.mdi-file-file-download
                  %i.mdi-action-visibility
                %h4.list-group-item-heading Ex.ua
                %p.list-group-item-text онлайн та скачування
          .list-group-separator
        - if @series_presenter.source_mirror_additional
          = link_to @series_presenter.source_mirror_additional, target: '_blank', class: 'btn special-button' do
            .list-group-item
              .row-action-primary
                %i.mdi-social-people.vk-com
              .row-content
                .action-secondary
                  %i.mdi-action-visibility
                %h4.list-group-item-heading Vk.com
                %p.list-group-item-text онлайн перегляд

app/views/series/_episode_fields.haml
.field.episode-section
  = f.label :episode_number, class: 'col-sm-2 control-label'
  .col-sm-10
    %p
      = f.text_field :episode_number, class: 'form-control', placeholder: 'Номер епізоду чи ова ( 1, 2, 3, OVA, OVA2 ...)'
  .clearfix
  = f.label :name, class: 'col-sm-2 control-label'
  .col-sm-10
    %p
      = f.text_field :name, class: 'form-control', placeholder: 'Назва окремого епізоду, якщо є'
  .clearfix
  = f.label :video_link, class: 'col-sm-2 control-label'
  .col-sm-10
    %p
      = f.text_field :video_link, class: 'form-control', placeholder: 'Поки лише лінк на Мету. приклад: http://video.meta.ua/7286223.video'
  .clearfix
  %p
    = f.hidden_field :_destroy
  .form-group
    .pull-right
      = link_to 'remove', 'javascript:void(0)', onclick: 'removeFields(this)', class: 'btn btn-danger btn-xs'

app/views/series/_form.html.haml
.well.bs-component
  = simple_form_for @series, html: { class: 'form-horizontal', :multipart => true } do |f|
    %fieldset
      = f.error_notification
      %legend Series Form
      .form-group
        .col-sm-9
          %p &nbsp;
          = f.label 'Категорія *', class: 'col-sm-2 control-label'
          .col-sm-10.col-md-4
            = f.select :category_id, grouped_options(f.object.category_id), { prompt: 'Виберіть зі списку...'}, {class: 'form-control', label: false }
          .clearfix
          %p &nbsp;
          = f.label 'Назва публікації *', class: 'col-sm-2 control-label'
          .col-sm-10
            = f.input :name, class: 'form-control', placeholder: 'Series name', label: false
          .clearfix
          %p &nbsp;
          = f.label :original_name, class: 'col-sm-2 control-label'
          .col-sm-10
            = f.input :original_name, class: 'form-control', placeholder: 'Original name', label: false
          .clearfix
          %p &nbsp;
          = f.label 'Опис *', class: 'col-sm-2 control-label'
          .col-sm-10
            = f.text_area :description, class: 'form-control', placeholder: 'Series description', label: false, rows: 5
          .clearfix
          %p &nbsp;
          = f.label :tag_list, class: 'col-sm-2 control-label'
          .col-sm-10
            = f.text_field :tag_list, class: 'form-control', placeholder: 'Series description', label: false, "data-role" => "tagsinput", value: @series.tag_list.join(',')
          .clearfix
          %p &nbsp;
          = f.label :episodes_amount, class: 'col-sm-2 control-label'
          .col-sm-10
            .col-sm-3.select-delimiter
              = f.select :episodes_amount, 1..150, {}, {class: 'form-control', placeholder: 'Загальна кількість серій', label: false }
            .col-sm-9.select-delimiter
              = f.label :episode_time, class: 'col-sm-4 control-label pull-left select-delimiter'
              .col-sm-8.select-delimiter
                = f.input :episode_time, class: 'form-control', placeholder: 'Продовжуваність однієї серії', label: false
          .clearfix
          %p &nbsp;
          = f.label :year, class: 'col-sm-2 control-label'
          .col-sm-10
            .col-sm-2.select-delimiter
              = f.select :year, (1980..Date.current.year).to_a.reverse, {}, {class: 'form-control', placeholder: 'Рік виходу', label: false }
          .clearfix
          %p &nbsp;
          = f.label :studio_name, class: 'col-sm-2 control-label'
          .col-sm-10
            = f.input :studio_name, class: 'form-control', placeholder: 'Назва студії', label: false
          .clearfix
          %p &nbsp;
          = f.label :video_info, class: 'col-sm-2 control-label'
          .col-sm-10
            = f.input :video_info, class: 'form-control', placeholder: 'Відео формат', label: false
          .clearfix
          %p &nbsp;
          = f.label :audio_info, class: 'col-sm-2 control-label'
          .col-sm-10
            = f.input :audio_info, class: 'form-control', placeholder: 'Аудіо формат', label: false
          .clearfix
          %p &nbsp;
          = f.label :translator, class: 'col-sm-2 control-label'
          .col-sm-10
            = f.input :translator, class: 'form-control', placeholder: 'Переклад', label: false
          .clearfix
          %p &nbsp;
          = f.label :actors, class: 'col-sm-2 control-label'
          .col-sm-10
            = f.input :actors, class: 'form-control', placeholder: 'Текст читали', label: false
          .clearfix
          %p &nbsp;
          = f.label :sound_maker, class: 'col-sm-2 control-label'
          .col-sm-10
            = f.input :sound_maker, class: 'form-control', placeholder: 'Робота зі звуком', label: false
          .clearfix
          %p &nbsp;
          = f.label :executer, class: 'col-sm-2 control-label'
          .col-sm-10
            = f.input :executer, class: 'form-control', placeholder: 'Виконавець', label: false
          .clearfix          

        .col-sm-3
          .col-sm-12
            .poster-holder
              %p
                %b Постер *
              %p
                .upload-preview
                  = image_tag (@series.cover.url(secure: true))
              %p
                %input.form-control.floating-label.pointer{:placeholder => "Browse...", :readonly => "", :type => "text", value: @series.cover_name }
                = f.file_field :cover, placeholder: 'Select the cover', class: 'pointer'
                = f.hidden_field(:cover_cache)
          .clearfix
          .col-sm-12
            .poster-holder
              %p
                %b Посилання на торрент трекер
              %p
                = f.text_field :torrent, class: 'form-control', placeholder: 'Torrent tracker'
          .col-sm-12
            .poster-holder
              %p
                %b Реліз на Ex.ua
              %p
                = f.text_field :source_mirror, class: 'form-control', placeholder: 'Ex.ua посилання'
          .col-sm-12
            .poster-holder
              %p
                %b Реліз в Vk.com
              %p
                = f.text_field :source_mirror_additional, class: 'form-control', placeholder: 'Вк посилання'

        .clearfix
        .col-sm-12
          .col-sm-1
          .col-sm-8
            %h4 Episodes:
            .fields.form-group
              = f.fields_for :episodes, f.object.episodes.order(:created_at) do |builder|
                = render 'episode_fields', f: builder
            %hr
            .form-group
              .col-sm-8
                = link_to_add_fields 'Add Episode', f, :episodes
            %hr

      .form-group
        .col-sm-8
          .buttons-holder.pull-right
            = link_to 'Назад', series_index_path, class: 'btn btn-default'
            = f.button :submit, 'Зберегти', class: 'btn btn-primary'

:javascript
  addPostponedFunc(['allScriptsReady'],function(){
    var preview = $(".upload-preview img");

    $("#series_cover").change(function(event){
       var input = $(event.currentTarget);
       var file = input[0].files[0];
       var reader = new FileReader();
       reader.onload = function(e){
           image_base64 = e.target.result;
           preview.attr("src", image_base64);
       };
       reader.readAsDataURL(file);
    });
  });

  addPostponedFunc(['allScriptsReady'],function(){
    var preview = $(".torrent-preview img");

    $("#series_torrent").change(function(event){
       var input = $(event.currentTarget);
       var file = input[0].files[0];
       var reader = new FileReader();
       reader.onload = function(e){
           image_base64 = e.target.result;
           preview.attr("src", '#{asset_path("success.png")}');
       };
       reader.readAsDataURL(file);
    });
  });

app/views/series/_settings_panel.html.haml
.settings-panel
  .panel.panel-info
    .panel-body
      %h4 Series settings
      .list-group
        .list-group-item
          .row-action-primary.checkbox
            %label
              %input{:type => "checkbox", checked: false, disabled: true}/
          .row-content
            %h5.list-group-item-heading Плейлист?
            %p.list-group-item-text Автоматичне перемикання на наступну серію
        .list-group-separator
        .list-group-item
          .row-action-primary.checkbox
            %label
              %input{:type => "checkbox", checked: true, disabled: true}/
          .row-content
            %h5.list-group-item-heading Пропускати вступ і титри
            %p.list-group-item-text Автоматичне пропускати опенінг та ендінг
        .list-group-separator
        .list-group-item
          .row-action-primary.checkbox
            %label
              %input{:type => "checkbox", checked: false, disabled: false}/
          .row-content
            %h5.list-group-item-heading Улюблене
            %p.list-group-item-text Закріпити в профілі

app/views/series/_single_post.html.haml
.post
  .panel.panel-default
    .post-image
      = link_to series_path(series_presenter.native) do
        .image{class: "series_#{series_presenter.native.id}"}
          .inside-image{style: "background-image: url('#{series_presenter.cover.url(secure: true).sub('/upload/', '/upload/c_scale,w_320/')}');background-size:cover;background-position: 100% 5%"}
    .post-content
      .post-heading
        .title.col-xs-11
          = link_to series_presenter.name, series_path(series_presenter.native)
        .additional.col-xs-1
          = link_to '', series_path(series_presenter.native), class: 'btn btn-white btn-fab btn-raised mdi-av-play-arrow pull-right round-sizer'
      .post-body
        .episode
          %i.mdi-av-movie.mdi-material-grey-700
          %span
            %b= "Епізод #{series_presenter.episodes_count} з #{series_presenter.episodes_amount}"
          .types.pull-right.visible-sm-inline.visible-md-inline.visible-lg-inline{style: 'padding-top:10px'}
            %span.label.label-primary.btn-sm= "torrent" if series_presenter.torrent
            %span.label.label-warning.btn-sm online
        .ellipsis
          %p.visible-sm.visible-md.visible-lg
            %b Опис:
          = series_presenter.description
        .labels
          %i.mdi-action-loyalty.mdi-material-grey-700
          = series_presenter.categories

app/views/series/edit.html.haml
= render 'form'

= link_to 'Show', @series
\|
= link_to 'Back', series_index_path

app/views/series/index.html.haml
- content_for :title do
  = 'Всі релізи'
- content_for :description do
  = "Всі релізи - UkrDub - це вітчизняний фандаб проект, що займається перекладом і озвученням аніме та серіалів українською мовою." 
- content_for :url do
  = request.original_url  

.row
  .col-sm-12
    %ul.breadcrumb
      %li
        = link_to 'Головна', root_path
      %li.active Всі релізи
.row
  .col-lg-8
    - @series_presenter.each do |series_presenter|
      = render 'series/single_post', series_presenter: series_presenter
    %br
    .center-block{style: 'height: 78px'}
      = will_paginate @series, renderer: BootstrapPagination::Rails

  .col-lg-4
    = render 'layouts/last_comments'

app/views/series/load_tile.js.erb
window.series_<%= @series.id %> = '<%= escape_javascript(render partial: 'series/cover_ajax', locals: { cover: @series_presenter.cover, category_id: @series_presenter.category.id }) %>';
$(".series_<%= @series.id %>")
  .empty()
  .append(window.series_<%= @series.id %>)
  .find('.inside-image')
  .fadeIn( 1000 );

app/views/series/load_tile_cover.js.erb
window.series_cover<%= @series.id %> = '<%= escape_javascript(render partial: 'series/cover_url_ajax', locals: { cover: @series_presenter.cover}) %>';
$(".series_cover<%= @series.id %>")
  .empty()
  .append('<img src=' + window.series_cover<%= @series.id %> + ' width="100%" />');

app/views/series/new.html.haml
%h1 New series

= render 'form'

= link_to 'Back', series_index_path

app/views/series/show.html.haml
- content_for :title do
  = "#{@series_presenter.name} / #{@series_presenter.native.original_name}" 
- content_for :url do
  = series_url(@series_presenter.native)
- content_for :description do
  = @series_presenter.description 
- content_for :image do
  = cl_image_path("files/series/#{@series_presenter.native.id}/cover.jpg", :width=>537, :height=>240, :crop=>:thumb, :secure => true)
  -#"http://res.cloudinary.com/ukrdub/image/upload/c_thumb,h_240,w_537/v1444595190/files/series/#{@series_presenter.native.id}/cover.jpg"

.row
  .col-sm-12
    %ul.breadcrumb
      %li
        = link_to 'Головна', root_path
      - if @series_presenter.category.parent
        %li
          = link_to @series_presenter.category.parent.try(:name), category_path(@series_presenter.category.parent)
      %li
        = link_to @series_presenter.category.name, category_path(@series_presenter.category)
      %li.active= @series_presenter.name
.row
  .col-lg-9
    .open-post
      .panel.panel-default.top-round
        .post-content
          .panel-body
            .col-sm-4.plotter-left-5.plotter-right-5
              %div.post-cover{ class: "series_cover#{@series_presenter.native.id}" }
              :javascript
                addPostponedFunc(['allScriptsReady'],function(){
                  if (window.series_cover#{@series_presenter.native.id} != undefined) {
                    $('.series_cover#{@series_presenter.native.id}')
                      .empty()
                      .append('<img src=' + window.series_cover#{@series_presenter.native.id} + ' width="100%" />')
                  } else {
                    $.getScript('#{ load_tile_cover_path(@series_presenter.native) }');
                  }
                })
            .col-sm-8
              .describe-items
                .row
                  .col-sm-12
                    .col-sm-12
                      %h4
                        %a
                          %b
                            = @series_presenter.name
                      %span= @series_presenter.original_name
                      %br
                      - if admin?
                        %span.pull-right
                          %span= link_to 'Редагувати', edit_series_path(@series)
                          \|
                          %span= link_to 'Видалити', @series, :method => :delete, :data => { :confirm => 'Впевнений?' }

                  .col-sm-12
                    .col-sm-3
                      %span.titles Жанр:
                    .col-sm-9
                      %span
                        = @series_presenter.categories
                  .col-sm-12
                    .col-sm-3
                      %span.titles Серій:
                    .col-sm-9
                      %span= @series_presenter.episodes_amount_and_time
                  .col-sm-12
                    .col-sm-3
                      %span.titles Рік виходу:
                    .col-sm-9
                      %span= @series_presenter.year
                  .col-sm-12
                    .col-sm-3
                      %span.titles Студія:
                    .col-sm-9
                      %span= @series_presenter.studio_name
                  .col-sm-12
                    .col-sm-3
                      %span.titles Відео:
                    .col-sm-9
                      %span= @series_presenter.video_info
                  .col-sm-12
                    .col-sm-3
                      %span.titles Звук:
                    .col-sm-9
                      %span= @series_presenter.audio_info

                  .col-sm-12
                    .col-sm-3
                      %span.titles Переклад:
                    .col-sm-9
                      %span= @series_presenter.translator
                  .col-sm-12
                    .col-sm-3
                      %span.titles Текст читали:
                    .col-sm-9
                      %span
                        = @series_presenter.actors
                  .col-sm-12
                    .col-sm-3
                      %span.titles Робота зі звуком:
                    .col-sm-9
                      %span
                        = @series_presenter.sound_maker
                  - if @series_presenter.executer.present?
                    .col-sm-12
                      .col-sm-3
                        %span.titles Виконано:
                      .col-sm-9
                        %span
                          = @series_presenter.executer                        

                  .col-sm-12.text-justify
                    %p &nbsp;
                    %p
                      .col-sm-12
                        %p
                          %span.titles Опис:
                        %span= @series_presenter.description

            %p.clearfix
            %hr
            .video-content
              .col-sm-8.plotter-right.plotter-left-5
                #task-form

              .col-sm-4.plotter-left.plotter-right
                .list-of-episodes
                  - @episodes_presenter.reverse.each_with_index do |episode, index|
                    = link_to(episode_path(episode.id), remote: true) do
                      .panel.panel-default.btn{ class: "#{ "active_episode" if index == 0 }"}
                        .media
                          .media-left
                            = image_tag episode.thumbnail, class: 'media-object', size: '100x70'
                          .media-body
                            %h6.media-heading= episode.episode_number
                            %span= episode.name



    .comments
      = render 'layouts/last_comments'


  .col-lg-3
    = render 'series/downloads_panel'
  %script{:type => "application/ld+json"}
    {
    "@context": "http://schema.org",
    "@type": "TVSeries",
    "image": "#{yield(:image)}",
    "author": {
    "@type": "Organization",
    "name": "#{@series_presenter.studio_name}"
    },
    "name": "#{@series_presenter.name}",
    "description": "#{@series_presenter.description}"
    }

  
  :javascript
    var url = '#{ @series_presenter.default_meta_video }';
    addPostponedFunc(['cssLoaded'], function(){
      var frameHolder = document.getElementById('task-form');
      setTimeout(function(){
        frameHolder.innerHTML = '<iframe frameborder="0" height="428" scrolling="no" src="' + url + '" width="100%"></iframe>'
      }, 2000);
    })
  